### PR TITLE
Add support for navbars

### PR DESCRIPTION
**Pull request by Tutuchan**
Hi, 

I just tweaked the html template and the css for readthedown to allow for navbars. 

The code added to `readthedown.html` is straight up pasted from the `rmarkdown` package, I'm not 100% sure how ok it is to do this.

### CODE REVIEW

**Comment by juba** [comment]
Hi,

And thanks for your pull request.

To be frank, I'm not totally convinced with navbars for `readthedown` as it is... The functionality could totally be useful, but the presentation doesn't seem optimal right now. The navbar adds a bit of clutter visually, and if you switch to a mobile view, you get two toggle menu buttons : one for the navbar menu, the other one for the table of contents.

I don't really know what could be done : duplicate `readthedown` with a redesigned or hidden table of contents ? Find another more compatible navbar design ?

What do you think about it ?

As per copying code from `rmarkdown`, I don't think it's a problem as the package is released under GPLv3. We should just be sure to source and credit them in the function documentation.

**Comment by Tutuchan** [comment]
Yeah I hesitated filing the PR, I hacked this together for my own needs and I figured I would do the PR in case somebody else would be interested but I wasn't sure it was the direction you wanted to go with the format/package.

I didn't think about the mobile view, that's my bad. I do agree the navbar adds some clutter and I don't think the table of contents should change, if you want to keep the design close to `readthedocs`. 

Breadcrumbs could be a less intrusive solution but navigation between files wouldn't be as easy as with the navbar.
Having a vertical navbar-equivalent on the right side of the page could help reduce the clutter but I don't think it will look good.
Another option would be to have a behavior closer to `readthedocs` where multiple files can be referenced in the table of contents but I think that's outside the scope of this package (and close to what the [bookdown](https://github.com/rstudio/bookdown) package aims to do).

**Comment by jemus42** [comment]
I'm interested in using this for an Rmd-website, would it fix [this current state](http://stats.jemu.name/qm/experiments/rmd-web/_site/Aufgabe06.html)?

**Comment by Tutuchan** [comment]
Hi, yes it would, that was the point of my changes. 

Unfortunately I cleaned my repositories a bit a couple of days ago and I deleted my fork but you can make your own fork and copy/paste these changes and it should work.

**Pull request closed without merging**
